FROM mcr.microsoft.com/playwright:v1.44.1-jammy

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . .


# Command to run Playwright tests
CMD ["npm", "run", "test:e2e"]
