services:
  front:
    image: ps6-front
    build: 
      context: ../front-end
      dockerfile: Dockerfile
      args:
        - SERVER_URL=http://back:9428/api
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      back:
        condition: service_healthy
    
    
  
  back:
    image: ps6-back
    build: 
      context: ../backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=e2e
    ports:
      - "8081:9428"
    volumes:
      - ../backend/database:/app/database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9428/api/status"]
      interval: 10s
      timeout: 10s
      retries: 5

  playwright:
    image: ps6-playwright
    build: 
      context: ../front-end
      dockerfile: Dockerfile.e2e
    environment:
      - FRONT_URL=http://front:80
    depends_on:
      front:
        condition: service_healthy
      back:
        condition: service_healthy
    volumes:
      - ./test-results:/usr/src/app/test-results
    

volumes:
  back_data:
  test_results:
 
